import type { Metadata } from "next";
// 1. Change the import from Inter to Montserrat
import { Montserrat } from "next/font/google";
import "./globals.css";

// 2. Initialize the new font
const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: ['400', '600', '700'] 
});

export const metadata: Metadata = {
  title: "A Special Surprise!",
  description: "A birthday surprise generated by Aryan & Devarsh for Janki",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* 3. The <link> tags are no longer needed and can be removed */}
      </head>
      {/* 4. Apply the new font's class name to the body */}
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
